language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ngoclam9412/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ngoclam9412/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-303508780854"
  bucket_path: "docker-react" #SAME AS APP
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"